package com.ironhack.FabFour_ForceOfSalesHomework3.enums;

public enum Command {
    NEW_LEAD("NEW LEAD"),
    NEW_SALESREP("NEW SALESREP"),
    SHOW_SALESREPS("SHOW SALESREPS"),
    LOOKUP_SALESREP("LOOKUP SALESREP"),
    SHOW_CONTACTS("SHOW CONTACTS"),
    SHOW_OPPORTUNITIES("SHOW OPPORTUNITIES"),
    SHOW_LEADS("SHOW LEADS"),
    SHOW_ACCOUNTS("SHOW ACCOUNTS"),
    LOOKUP_LEAD("LOOKUP LEAD"),
    EXPORT_LEADS("EXPORT LEADS"),
    LOOKUP_OPPORTUNITY("LOOKUP OPPORTUNITY"),
    EXPORT_OPPORTUNITIES("EXPORT OPPORTUNITIES"),
    LOOKUP_ACCOUNT("LOOKUP ACCOUNT"),
    LOOKUP_CONTACT("LOOKUP CONTACT"),
    EXPORT_ACCOUNTS("EXPORT ACCOUNTS"),
    CONVERT("CONVERT"),
    CLOSE_WON("CLOSE-WON"),
    CLOSE_LOST("CLOSE-LOST"),
    REPORT("REPORT"),
    HELP("HELP"),
    NONE(""),
    MEAN_EMPLOYEE_COUNT("MEAN EMPLOYEECOUNT"),
    MEDIAN_EMPLOYEE_COUNT("MEDIAN EMPLOYEECOUNT"),
    MAX_EMPLOYEE_COUNT("MAX EMPLOYEECOUNT"),
    MIN_EMPLOYEE_COUNT("MIN EMPLOYEECOUNT"),
    MEAN_QUANTITY("MEAN QUANTITY"),
    MEDIAN_QUANTITY("MEDIAN QUANTITY"),
    MAX_QUANTITY("MAX QUANTITY"),
    MIN_QUANTITY("MIN QUANTITY"),
    MEAN_OPPS_PER_ACCOUNT("MEAN OPPS PER ACCOUNT"),
    MEDIAN_OPPS_PER_ACCOUNT("MEDIAN OPPS PER ACCOUNT"),
    MAX_OPPS_PER_ACCOUNT("MAX OPPS PER ACCOUNT"),
    MIN_OPPS_PER_ACCOUNT("MIN OPPS PER ACCOUNT"),
    LEADBYSALESREP("REPORT LEAD BY SALESREP"),
    OPPBYSALESREP("REPORT OPPORTUNITY BY SALESREP"),
    WONBYSALESREP("REPORT CLOSED-WON BY SALESREP"),
    LOSTBYSALESREP("REPORT CLOSED-LOST BY SALESREP"),
    OPENBYSALESREP("REPORT OPEN BY SALESREP"),
    OPPSBYPRODUCT("REPORT OPPORTUNITY BY THE PRODUCT"),
    WONBYPRODUCT("REPORT CLOSED-WON BY THE PRODUCT"),
    LOSTBYPRODUCT("REPORT CLOSED-LOST BY THE PRODUCT"),
    OPENBYPRODUCT("REPORT OPEN BY THE PRODUCT"),
    OPPBYCOUNTRY("REPORT OPPORTUNITY BY COUNTRY"),
    WONBYCOUNTRY("REPORT CLOSED-WON BY COUNTRY"),
    LOSTBYCOUNTRY("REPORT CLOSED-LOST BY COUNTRY"),
    OPENBYCOUNTRY("REPORT OPEN BY COUNTRY"),
    OPPBYCITY("REPORT OPPORTUNITY BY CITY"),
    WONBYCITY("REPORT CLOSED-WON BY CITY"),
    LOSTBYCITY("REPORT CLOSED-LOST BY CITY"),
    OPENBYCITY("REPORT OPEN BY CITY"),
    OPPBYINDUSTRY("REPORT OPPORTUNITY BY INDUSTRY"),
    WONBYINDUSTRY("REPORT CLOSED-WON BY INDUSTRY"),
    LOSTBYINDUSTRY("REPORT CLOSED-LOST BY INDUSTRY"),
    OPENBYINDUSTRY("REPORT OPEN BY INDUSTRY"),
    SHOWCOUNTRY("SHOW COUNTRY LIST");

    public final String value;

    private Command(String value) {
        this.value=value;
    }

    public static Command getCommandType(String sValue) {
        for (Command command: values()) {
            if(command.value.equals(sValue))
                return command;
        }
        return Command.NONE;
    }
}
